//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLPK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Giuong
    {
        public string MaGiuong { get; set; }
        public string STT { get; set; }
        public string Phong { get; set; }
    
        public virtual Phong Phong1 { get; set; }
    }
}
